# Generated by Django 5.0.6 on 2024-07-03 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auction_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_type',
        ),
    ]
