# Generated by Django 5.0.6 on 2024-07-03 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auction_app', '0002_remove_customuser_profile_pic_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
