# Generated by Django 5.0.6 on 2024-08-02 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auction_app', '0004_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='registrationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=50)),
                ('date_of_birth', models.DateTimeField()),
                ('mobile_no', models.CharField(max_length=10)),
                ('seller_or_bidder', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
