# Generated by Django 5.0.6 on 2024-08-30 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auction_app', '0013_admin_notification_seller_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_notification',
            name='status',
            field=models.ImageField(default=0, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='seller_notification',
            name='status',
            field=models.ImageField(default=0, null=True, upload_to=''),
        ),
    ]
