# Generated by Django 5.0.6 on 2024-08-30 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auction_app', '0014_admin_notification_status_seller_notification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_notification',
            name='status',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='seller_notification',
            name='status',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
